### ISSUE TITLE
How would I run a custom command?

### ISSUE THREAD

**Issue by norseghost** [cerebrate/wabash#6]
Hi. I have a POP3 email proxy I'd like to run (github.com/dk/Net-Eboks), but can't figure out how to run a custom service (well, running a perl script in the background) with wabashd.

I've tried the included debian rc script (errors out), writing an upstart thing (also errors out), and adding the command to /etc/rc,local (seems to do nothing), with corresponding /usr/bin/wabashd.exe.config entries.

**Comment by cerebrate** [comment]
I may not be the best person to ask about this, I'm afraid, mostly because I'm much less familiar with the Linux side of WSL than with the Windows side.

Basically, wabashd will start anything that can be controlled through _/usr/sbin/service_ (which is to say, System V init scripts or upstart jobs), per _man 8 service_, by listing the service name in _wabash.exe.config_ (note, not _wabashd.exe.config_; this is done on the Windows side).

From what I know of how this works, the included rc script ( https://github.com/dk/Net-Eboks/blob/master/example/eboks2pop.debian ) placed in /etc/init.d ought to make it controllable this way, and I don't see anything obviously wrong with it, or at least I'm not sufficiently familiar with the Linux daemon-management methodology to spot it.

All of which is to say "if you can get it to start and stop manually with _service(8)_, it'll work with wabash, but making that work is a bit beyond my expertise; try http://askubuntu.com/ ?" Sorry.

**Comment by norseghost** [comment]
Ok.

I shall intensify my efforts into getting the init script working.

If I place the example config next to wabash.exe, I get an error- can't
remember the specific text, but something about invalid side-by-side
configuration.

**Comment by cerebrate** [comment]
You shouldn't need to place another config there: there should be a _wabash.exe.config_ there already. If you open that up in an editor, there's a section that looks like this by default:

```
    <applicationSettings>
        <ArkaneSystems.Wabash.Properties.Settings>
            <setting name="Services" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>rsyslog</string>
                        <string>binfmt-support</string>
                        <string>dbus</string>
                        <string>cron</string>
                        <string>atd</string>
                    </ArrayOfString>
                </value>
            </setting>
        </ArkaneSystems.Wabash.Properties.Settings>
    </applicationSettings>
```

If you add a new line reading _`<string>eboks2pop</string>`_ (or whatever the name of your init script is in between the _`<string>`_ tags) next to the other service names in the middle of this section, that should be all the config you need to do for wabash, as long as the init script is working.

**Comment by norseghost** [comment]
Huh. I installed wabash with chocolatey, and didn't find it.

**Comment by cerebrate** [comment]
...oops, I've just realized a problem with the documentation.

I'm guessing you're looking at the wabash.exe in _/ProgramData/Chocolatey/bin_? There's not one there because that's not the "real" wabash.exe, that's the chocolatey-created shim which points at the actual wabash.exe in _/ProgramData/Chocolatey/lib/wabash/tools_. **That** one should have the wabash.exe.config next to it.

Thanks, and I'll update the README.

**Comment by norseghost** [comment]
:D

**Comment by norseghost** [comment]
so... turns out, this was classic PEBKAC... I'd forgotten to account for windows line endings. A quick CRLF -> LF conversion, and off to the races i went.
